### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by stef-otpyrc** [shinyscorpion/wobserver#52]
Trying to get some attention from the devs, what's going on, where is the new version?
https://github.com/shinyscorpion/wobserver/issues/44

**Comment by epinault** [comment]
Most likely dead . I made a request to Hex.pm to takeover the package in hex.pm. We will see in 30 days

meanwhile I posted this https://github.com/epinault/wobserver on other issues that I fixed. We can now use it with Phoenix 1.4

**Comment by shovelend** [comment]
> Most likely dead . I made a request to Hex.pm to takeover the package in hex.pm. We will see in 30 days
> 
> meanwhile I posted this https://github.com/epinault/wobserver on other issues that I fixed. We can now use it with Phoenix 1.4

@epinault Thanks for your serious efforts. I am using your forked version and trying to make Phoenix 1.4 work with little to no luck. It's still complaining about 
```
** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) function Wobserver.Web.PhoenixSocket.child_spec/1 is undefined or private
            (wobserver) Wobserver.Web.PhoenixSocket.child_spec([endpoint: MyWeb.Endpoint])
            (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
            (phoenix) lib/phoenix/endpoint/supervisor.ex:56: Phoenix.Endpoint.Supervisor.init/1
            (stdlib) supervisor.erl:295: :supervisor.init/1
            (stdlib) gen_server.erl:374: :gen_server.init_it/2
            (stdlib) gen_server.erl:342: :gen_server.init_it/6
            (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```
Do you happen to know how I should fix this compilation error?

**Comment by jrgvf** [comment]
Guys, try without use Wobserver.Web.PhoenixSocket in endpoint.ex and it's work.
The Wobserver application start already make the 'magic' for us.

**Comment by rwngallego** [comment]
@epinault have you have any luck in taking over the project? There's a lot of issues with old dependencies. It would be great to at least solve these issues.

**Comment by axelson** [comment]
In addition to @epinault's fork there is this hex package: https://hex.pm/packages/wobserverfork which I believe originates from https://github.com/alfonsoperez/wobserver

**Comment by epinault** [comment]
I need to ask the hex.pm maintainer. he asked for my email but I don t see that I own the package on hex.pm. Will check tomorrow

**Comment by antoniobg** [comment]
@shovelend did you manage to run it on Phoenix 1.4?

**Comment by jmn** [comment]
Any updates on getting this to run on recent versions?

**Comment by liyu1981** [comment]
I forked it and made it working under current Elixir 1.14 with Erlang/OTP 25, at here: https://github.com/liyu1981/wobserver-ng. If you are interested please try. 

I intentionally want to keep making it updated with Elixir new versions in my spare time.

**Comment by epinault** [comment]
Ah thanks . I moved on to use Phoenix live dashboard the last few years
